### ISSUE TITLE
retry on "configuration version still processing" error prior to run create

### ISSUE THREAD

**Issue by lucymhdavies** [mitchellh/terraform-provider-multispace#9]
### Terraform Version
```
$ terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.26.1
+ provider registry.terraform.io/mitchellh/multispace v0.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- multispace_run

### Terraform Configuration Files
```hcl
resource "tfe_workspace" "child" {
  name = "multispace-child"

  description  = "Child Workspace"
  organization = "hashi_strawb_testing"
  auto_apply   = true

  vcs_repo {
    identifier     = "lucymhdavies/terraform-provider-multispace"
    oauth_token_id = "ot-TZxcR8MRaTRvteFL"
    branch         = "main"
  }
  working_directory = "test/noop"

  queue_all_runs = false
}

resource "multispace_run" "child" {
  workspace    = tfe_workspace.child.name
  organization = "hashi_strawb_testing"
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/lucymhdavies/6c9edec17329989c388d8cf969d0dd32

### Expected Behavior
What should have happened?

* Workspace created
* Multispace Run triggered

### Actual Behavior
What actually happened?

* Workspace created
* Multispace Run failed

### Steps to Reproduce

A Terraform Apply with the provided code should be sufficient to reproduce the issue.

The issue is intermittent, so may need a few tries before it can be replicated.

### Important Factoids
Nothing special, just a standard TFC4B Org

**Comment by lucymhdavies** [comment]
Potentially the same thing that the Terraform CLI does should work for this:
https://github.com/hashicorp/go-tfe/issues/116#issuecomment-684842094
>Terraform CLI waits for the status to change before creating the run: >https://github.com/hashicorp/terraform/blob/v0.13.1/backend/remote/backend_plan.go#L204-L231

**Comment by mitchellh** [comment]
It looks like I am just completely ignoring an error result there. Whoops! That would account for it. I should probably run `go vet` against this codebase. There's still a possibility that for certain error scenarios we want to retry, "configuration still processing" is probably one of those. Let me first at least handle the error so we don't panic...

**Comment by mitchellh** [comment]
Uhh, reopening and going to rename to address the "config version still processing" thing.

**Comment by lucymhdavies** [comment]
With functionality from this provider being incorporated into the main TFE provider...
https://github.com/hashicorp/terraform-provider-tfe/issues/742

I'm gonna close this off.
